package ru.voidrp.asyncai.mixin;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.chunk.LevelChunk;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;
import ru.voidrp.asyncai.ChunkWarnRateLimit;
import ru.voidrp.asyncai.CurrentCommandPlayer;
import ru.voidrp.asyncai.VoidRpAsyncAI;

/**
 * Guards CraftWorld.getChunkAt(int, int) against main-thread deadlock
 * when the destination chunk is not yet loaded.
 *
 * Root cause (Watchdog dump 2026-05-27 11:48):
 *   EssentialsX AsyncTeleport.nowAsync() → PaperLib.getChunkAtAsync
 *   → AsyncChunksSync.getChunkAtAsync (sync fallback — PaperLib does not detect Youer as Paper)
 *   → CraftWorld.getChunkAt → Level.getChunk → ServerChunkCache.getChunk(require=true)
 *   → managedBlock → waitForTasks → parkNanos
 *   Distant chunk generation takes 10-60+ seconds, Watchdog fires at 10 s → auto-restart.
 *
 * Fix: when getChunkAt is called from the main thread for a not-yet-loaded chunk,
 * return null immediately. EssentialsX's CompletableFuture chain fails exceptionally
 * (teleport silently cancelled). Player retries /tp a few seconds later when the chunk
 * has been pre-generated by the normal async pipeline.
 *
 * Non-main-thread callers fall through to normal (potentially blocking) behavior,
 * which is acceptable on worker threads.
 */
@Mixin(targets = "org.bukkit.craftbukkit.CraftWorld", remap = false)
public abstract class CraftWorldGetChunkMixin {

    @Shadow public abstract ServerLevel getHandle();

    @Inject(
        method = "getChunkAt(II)Lorg/bukkit/Chunk;",
        at = @At("HEAD"),
        cancellable = true,
        require = 0
    )
    private void voidrp_guardGetChunkAt(int x, int z, CallbackInfoReturnable<Object> cir) {
        if (!"Server thread".equals(Thread.currentThread().getName())) return;

        ServerLevel level = getHandle();
        if (level.getChunkSource().getChunkNow(x, z) != null) return; // already loaded, fall through safely

        // Main thread + unloaded chunk → would park in managedBlock 10-60 s → Watchdog fires.
        // Fix: return null immediately (prevents hang), AND trigger async chunk loading via
        // Paper's World.getChunkAtAsync() so the player's retry succeeds in ~5-10 seconds.
        try {
            // level.getWorld() returns org.bukkit.World — call via reflection (Bukkit not on classpath)
            Object world = level.getClass().getMethod("getWorld").invoke(level);
            if (world != null) {
                // World.getChunkAtAsync(int,int) — starts async generation, returns CompletableFuture
                world.getClass().getMethod("getChunkAtAsync", int.class, int.class).invoke(world, x, z);
            }
        } catch (Exception ignored) {
            // Async API not available in this runtime — chunk won't pre-load, player retries manually
        }

        // Notify the player in Russian so they know what happened
        ServerPlayer cmdPlayer = CurrentCommandPlayer.get();
        if (cmdPlayer != null) {
            cmdPlayer.sendSystemMessage(
                Component.literal("⏳ Чанк ещё не загружен. Загрузка начата — повтори команду через ~10 секунд.")
                    .withStyle(ChatFormatting.YELLOW)
            );
        }

        long suppressed = ChunkWarnRateLimit.acquire(x, z);
        if (suppressed >= 0) {
            VoidRpAsyncAI.LOGGER.warn(
                "[VoidRP] CraftWorld.getChunkAt main-thread guard — chunk [{},{}] not loaded, " +
                "async load started, returning null{}. Retry /tp or /home in ~10 seconds.",
                x, z, suppressed > 0 ? " (+" + suppressed + " suppressed)" : "");
        }
        cir.setReturnValue(null);
    }
}
